/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication14;

/**
 *
 * @author rohit
 */
public class pro1 extends javax.swing.JFrame
{

    /**
     * Creates new form pro1
     */
    public pro1()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addy = new javax.swing.JTextField();
        addsubmit = new javax.swing.JButton();
        addx = new javax.swing.JTextField();
        addanswer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        suby = new javax.swing.JTextField();
        subsubmit = new javax.swing.JButton();
        subx = new javax.swing.JTextField();
        subanswer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        multy = new javax.swing.JTextField();
        multsubmit = new javax.swing.JButton();
        multx = new javax.swing.JTextField();
        multanswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(13, 85, 158));

        jTabbedPane1.setBackground(new java.awt.Color(100, 225, 75));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.blue, java.awt.Color.lightGray, java.awt.Color.cyan), null));

        jPanel2.setBackground(new java.awt.Color(6, 128, 215));
        jPanel2.setAlignmentX(0.0F);

        jLabel1.setBackground(new java.awt.Color(51, 192, 238));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Two Numbers");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel1.setOpaque(true);

        addy.setBackground(new java.awt.Color(73, 215, 155));
        addy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Y:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        addy.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                addyKeyTyped(evt);
            }
        });

        addsubmit.setBackground(new java.awt.Color(225, 61, 47));
        addsubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addsubmit.setForeground(new java.awt.Color(247, 189, 20));
        addsubmit.setText("Submit");
        addsubmit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        addsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addsubmitActionPerformed(evt);
            }
        });

        addx.setBackground(new java.awt.Color(73, 215, 155));
        addx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        addx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addxActionPerformed(evt);
            }
        });
        addx.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                addxKeyTyped(evt);
            }
        });

        addanswer.setBackground(new java.awt.Color(51, 192, 238));
        addanswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addanswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        addanswer.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(addx, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addy, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addx, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(addsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(addanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Additon", jPanel2);

        jPanel3.setBackground(new java.awt.Color(100, 225, 75));

        jPanel5.setBackground(new java.awt.Color(255, 51, 255));
        jPanel5.setAlignmentX(0.0F);

        jLabel2.setBackground(new java.awt.Color(255, 153, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Two Numbers");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel2.setOpaque(true);

        suby.setBackground(new java.awt.Color(153, 102, 255));
        suby.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        suby.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Y:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        suby.setOpaque(true);
        suby.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                subyKeyTyped(evt);
            }
        });

        subsubmit.setBackground(new java.awt.Color(0, 0, 255));
        subsubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subsubmit.setForeground(new java.awt.Color(255, 255, 51));
        subsubmit.setText("Submit");
        subsubmit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(247, 189, 20)));
        subsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                subsubmitActionPerformed(evt);
            }
        });

        subx.setBackground(new java.awt.Color(153, 102, 255));
        subx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        subx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                subxActionPerformed(evt);
            }
        });
        subx.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                subxKeyTyped(evt);
            }
        });

        subanswer.setBackground(new java.awt.Color(255, 153, 204));
        subanswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subanswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        subanswer.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(subx, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(suby, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(subsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(subanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subx, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suby, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(subsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(subanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Subtraction", jPanel3);

        jPanel4.setBackground(new java.awt.Color(127, 150, 47));

        jPanel6.setBackground(new java.awt.Color(204, 204, 0));
        jPanel6.setAlignmentX(0.0F);

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter Two Numbers");
        jLabel5.setToolTipText("");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel5.setOpaque(true);

        multy.setBackground(new java.awt.Color(153, 153, 0));
        multy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Y:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        multy.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                multyKeyTyped(evt);
            }
        });

        multsubmit.setBackground(new java.awt.Color(51, 255, 0));
        multsubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        multsubmit.setForeground(new java.awt.Color(51, 51, 255));
        multsubmit.setText("Submit");
        multsubmit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        multsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                multsubmitActionPerformed(evt);
            }
        });

        multx.setBackground(new java.awt.Color(153, 153, 0));
        multx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        multx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                multxActionPerformed(evt);
            }
        });
        multx.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                multxKeyTyped(evt);
            }
        });

        multanswer.setBackground(new java.awt.Color(255, 255, 0));
        multanswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        multanswer.setForeground(new java.awt.Color(255, 0, 0));
        multanswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        multanswer.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(multx, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multy, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(multsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(multanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multx, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(multsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(multanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Multiplication", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addxActionPerformed
    {//GEN-HEADEREND:event_addxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addxActionPerformed

    private void subxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_subxActionPerformed
    {//GEN-HEADEREND:event_subxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subxActionPerformed

    private void multxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_multxActionPerformed
    {//GEN-HEADEREND:event_multxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multxActionPerformed

    private void addxKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_addxKeyTyped
    {//GEN-HEADEREND:event_addxKeyTyped
            char ch=evt.getKeyChar();
            if(Character.isDigit(ch)==false) 
            {
                evt.consume();
            }
    }//GEN-LAST:event_addxKeyTyped

    private void addsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addsubmitActionPerformed
    {//GEN-HEADEREND:event_addsubmitActionPerformed
          String str1=this.addx.getText(); 
          String str2=this.addy.getText();
             
         
       
          if(this.addx.getText().equals("") &&  this.addy.getText().equals("")) 
          {
              this.addanswer.setText("");
          } 
          
          else if(!(this.addx.getText().equals(""))&&  this.addy.getText().equals("")) 
          { 
              int x=Integer.parseInt(str1);
              this.addanswer.setText(Integer.toString(x));
          } 
         else if( this.addx.getText().equals("") &&  !(this.addy.getText().equals("")))
          {   
              int y=Integer.parseInt(str2); 
              this.addanswer.setText(Integer.toString(y));
          }  
          else 
          { 
                  int x=Integer.parseInt(str1);
                 int y=Integer.parseInt(str2); 
              this.addanswer.setText(Integer.toString(x+y)); 
          }
          
           
          
    }//GEN-LAST:event_addsubmitActionPerformed

    private void addyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_addyKeyTyped
    {//GEN-HEADEREND:event_addyKeyTyped
         char ch=evt.getKeyChar();
            if(Character.isDigit(ch)==false) 
            {
                evt.consume();
            }
    }//GEN-LAST:event_addyKeyTyped

    private void subxKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_subxKeyTyped
    {//GEN-HEADEREND:event_subxKeyTyped
         char ch=evt.getKeyChar();
            if(Character.isDigit(ch)==false) 
            {
                evt.consume();
            }
    }//GEN-LAST:event_subxKeyTyped

    private void subyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_subyKeyTyped
    {//GEN-HEADEREND:event_subyKeyTyped
         char ch=evt.getKeyChar();
            if(Character.isDigit(ch)==false) 
            {
                evt.consume();
            }
    }//GEN-LAST:event_subyKeyTyped

    private void multsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_multsubmitActionPerformed
    {//GEN-HEADEREND:event_multsubmitActionPerformed
        String str1=this.multx.getText(); 
          String str2=this.multy.getText();
             
         
       
          if(this.multx.getText().equals("") &&  this.multy.getText().equals("")) 
          {
              this.subanswer.setText("");
          } 
          
          else if(!(this.multx.getText().equals(""))&&  this.multy.getText().equals("")) 
          { 
              int x=Integer.parseInt(str1);
              this.subanswer.setText(Integer.toString(x));
          } 
         else if( this.multx.getText().equals("") &&  !(this.multy.getText().equals("")))
          {   
              int y=Integer.parseInt(str2); 
              this.subanswer.setText(Integer.toString(y));
          }  
          else 
          { 
                  int x=Integer.parseInt(str1);
                 int y=Integer.parseInt(str2); 
              this.multanswer.setText(Integer.toString(x*y)); 
          }
          
    }//GEN-LAST:event_multsubmitActionPerformed

    private void multxKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_multxKeyTyped
    {//GEN-HEADEREND:event_multxKeyTyped
        char ch=evt.getKeyChar();
            if(Character.isDigit(ch)==false) 
            {
                evt.consume();
            }
    }//GEN-LAST:event_multxKeyTyped

    private void multyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_multyKeyTyped
    {//GEN-HEADEREND:event_multyKeyTyped
       char ch=evt.getKeyChar();
            if(Character.isDigit(ch)==false) 
            {
                evt.consume();
            }
    }//GEN-LAST:event_multyKeyTyped

    private void subsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_subsubmitActionPerformed
    {//GEN-HEADEREND:event_subsubmitActionPerformed
        // TODO add your handling code here: 
        String str1=this.subx.getText(); 
          String str2=this.suby.getText();
             
         
       
          if(this.subx.getText().equals("") &&  this.suby.getText().equals("")) 
          {
              this.subanswer.setText("");
          } 
          
          else if(!(this.subx.getText().equals(""))&&  this.suby.getText().equals("")) 
          { 
              int x=Integer.parseInt(str1);
              this.subanswer.setText(Integer.toString(x));
          } 
         else if( this.subx.getText().equals("") &&  !(this.suby.getText().equals("")))
          {   
              int y=Integer.parseInt(str2); 
              this.subanswer.setText(Integer.toString(y));
          }  
          else 
          { 
                  int x=Integer.parseInt(str1);
                 int y=Integer.parseInt(str2); 
              this.subanswer.setText(Integer.toString(x-y)); 
          }
          
    }//GEN-LAST:event_subsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(pro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(pro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(pro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(pro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new pro1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addanswer;
    private javax.swing.JButton addsubmit;
    private javax.swing.JTextField addx;
    private javax.swing.JTextField addy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel multanswer;
    private javax.swing.JButton multsubmit;
    private javax.swing.JTextField multx;
    private javax.swing.JTextField multy;
    private javax.swing.JLabel subanswer;
    private javax.swing.JButton subsubmit;
    private javax.swing.JTextField subx;
    private javax.swing.JTextField suby;
    // End of variables declaration//GEN-END:variables
}
